module sim_top (
    input wire clk,
    input wire rst,
    input wire cpu_enable,
    input wire bus_valid,
    input wire [3:0] bus_wstrb,
    input wire [31:0] bus_addr,
    input wire [31:0] bus_wdata,
    output wire [31:0] bus_rdata,
    output wire bus_ready,
    output wire bus_fault,
    output wire [7:0] leds,
    output wire uart_tx_strobe,
    output wire [7:0] uart_tx_data,
    input wire uart_rx_valid,
    input wire [7:0] uart_rx_data,
    output wire display_write_strobe,
    output wire display_is_command,
    output wire [7:0] display_write_data,
    output wire spi_sclk,
    output wire spi_mosi,
    output wire spi_cs_n,
    output wire spi_dc,
    output wire spi_rst_n,
    output wire [7:0] debug_status
);
    watchdog_koth_top dut (
        .clk(clk),
        .rst(rst),
        .cpu_enable(cpu_enable),
        .bus_valid(bus_valid),
        .bus_wstrb(bus_wstrb),
        .bus_addr(bus_addr),
        .bus_wdata(bus_wdata),
        .bus_rdata(bus_rdata),
        .bus_ready(bus_ready),
        .bus_fault(bus_fault),
        .leds(leds),
        .uart_tx_strobe(uart_tx_strobe),
        .uart_tx_data(uart_tx_data),
        .uart_tx_ready(1'b1),
        .uart_rx_valid(uart_rx_valid),
        .uart_rx_data(uart_rx_data),
        .display_write_strobe(display_write_strobe),
        .display_is_command(display_is_command),
        .display_write_data(display_write_data),
        .spi_sclk(spi_sclk),
        .spi_mosi(spi_mosi),
        .spi_cs_n(spi_cs_n),
        .spi_dc(spi_dc),
        .spi_rst_n(spi_rst_n),
        .debug_status(debug_status)
    );
endmodule
